### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by andyinabox** [chromice/order.less#4]
It would be nice to either add prefixes to the mixins and variables, or provide an alternate prefixed version of the .less stylesheet (similar to what [lesshat](https://github.com/madebysource/lesshat) does).

It gets kind of confusing when using this with other mixin libraries etc.

**Comment by chromice** [comment]
You can already do this using [Less Namespaces](http://lesscss.org/features/#mixins-feature-namespaces):

``` less
// You have to define your own global variables first
@prefix-grid-gutter: 20px;
@prefix-grid-width: 940px;
@prefix-grid-columns: 12;

// Put all .use-*() mixins into a namespace
#prefix {
    .use-column-grid(@prefix-grid-width, @prefix-grid-gutter, @prefix-grid-columns);
}

#content, #sidebar {
    float: left;
}

// Use the mixins exported into your namespace
#content {
    #prefix > .width(8);
}
#sidebar {
    #prefix > .width(4);
    #prefix > .margin-left(@prefix-grid-gutter);
}

```
